---
title: "practice"
output: html_document
date: "2026-08-03"
---


```{r}
machinery_change$share_over_20_0ha_2010
```

```{r}
df2 |>
  group_by(census_year) |>
  summarise(
    n = n(),
    n_individual_nonmissing = sum(!is.na(individual_entities)),
    n_individual_missing = sum(is.na(individual_entities)),
    min = min(individual_entities, na.rm = TRUE),
    max = max(individual_entities, na.rm = TRUE)
  )
```

```{r}
df2 |>
  filter(census_year %in% c("2010", "2015")) |>
  select(
    area_code,
    census_year,
    individual_entities,
    farm_entities_total
  ) |>
  arrange(area_code, census_year)
```


```{r}

library(tidyverse)
-124.84 + 0.853 * 30000


inc <- seq(0, 50000, by = 100)
cons_hat <- -124.84 + 0.853 * inc
apc <- -124.84 / inc + 0.853

df <- data.frame(inc = inc,
       cons_hat = cons_hat,
       apc = apc)

df |> ggplot(aes(x = inc)) +
  geom_line(aes(y = cons_hat, color = "cons_hat")) +
  geom_line(aes(y = apc, color = "apc"))


```
```{r}
inc <- seq(100, 50000, by = 100)

mpc <- rep(0.853, length(inc))
apc <- -124.84 / inc + 0.853

df <- data.frame(
  inc = inc,
  mpc = mpc,
  apc = apc
)

df |>
  ggplot(aes(x = inc)) +
  geom_line(aes(y = mpc, color = "MPC")) +
  geom_line(aes(y = apc, color = "APC"))
```


```{r}
124.84 / 0.853
```

```{r}
# (iii) 出生体重を 125オンス と予測するためには、\(cigs\) はいくつでなければならないでしょうか。結果についてコメントしなさい。
(119.77 - 125) / 0.514
```

cigsは負になる。モデルが線形であるため、データの傾向から外挿するとこのような非現実的な値が出ることがある。

また、妊娠中に喫煙しなかった女性の割合が0.85であるということは、cigs = 0のサンプルが全体の0.85であり、非常に多いということ。モデル全体がこのサンプルの傾向に引きずられていると思われる。


```{r}
# 母親が妊娠中にタバコを吸わなかった場合、予測される出生体重
119.77 - 0.514 * 0
df2 |> filter(census_year == "2010") |> select(area_name)

# 母親が1日1箱（20本）吸っていた場合、予測される出生体重
119.77 - 0.514 * 20
```
毎日タバコを20本吸うと、全く吸わないときに比べ、予測される出生体重は約10オンス低くなる。


```{r}
library(tidyverse)

df <- tibble(
  student = 1:8,
  gpa = c(2.8, 3.4, 3.0, 3.5, 3.6, 3.0, 2.7, 3.7),
  act = c(21, 24, 26, 27, 29, 25, 25, 30)
)
```

```{r}
beta_1 = sum((df$act - mean(df$act)) * (df$gpa - mean(df$gpa))) / 
  sum((df$act - mean(df$act))^2)

beta_1

beta_0 = mean(df$gpa) - beta_1 * mean(df$act)

beta_0

lm(gpa ~ act, data = df)
```

```{r}
m <- lm(gpa ~ act, data = df)

fitted_values <- m$coefficients[1] + m$coefficients[2] * df$act
residuals <- df$gpa - fitted_values

sum(residuals)
```

```{r}
# ACT = 20のときの予測値
m$coefficients[1] + m$coefficients[2] * 20
```

```{r}
m <- lm(gpa ~ act, data = df)
fitted_values <- m$coefficients[1] + m$coefficients[2] * df$act

sst <- sum((df$gpa - mean(df$gpa))^2)
sse <-  sum((fitted_values - mean(df$gpa))^2)
r_2 <- sse / sst
r_2

m_summary <- m |> summary()
m_summary$r.squared
```
GPAの変動の57.7%がACTで説明できる。

```{r}
m <- glm(
  production_support ~ tsunami_farmland_share,
  data = df2 |> filter(census_year == 2010),
  family = binomial
) 

m |> summary()

m$coefficients |> exp()


```

```{r}

```


```{r}
glm(
  c_one ~ tsunami_farmland_share,
  data = df2 |> filter(census_year == 2010),
  family = binomial
) |>
  summary()
```

```{r}
glm(
  production_support ~ tsunami_farmland_share,
  data = df2 |> filter(census_year == 2010),
  family = binomial
) |>
  summary()
```

```{r}
df2 |>
  filter(census_year == 2010) |>
  select(c_one, c_four, production_support) |>
  cor(use = "pairwise.complete.obs") |> round(2)

df_2010 <- df2 |>
  filter(census_year == 2010)

cor.test(df_2010$c_one, df_2010$c_four)
cor.test(df_2010$c_one, df_2010$production_support)
cor.test(df_2010$c_four, df_2010$production_support)
```




```{r}
df2 <- df2 |>
  mutate(
    share_over_20ha = entities_over_20_0ha / entities_total
  )

ggplot(
  df2,
  aes(
    x = tsunami_farmland_share,
    y = share_over_20ha
  )
) +
    geom_point(
    aes(color = factor(c_four)),
    size = 0.8
  ) +
  geom_smooth(
    method = "lm",
    se = FALSE,
    linewidth = 0.8
  ) +
  facet_wrap(
    ~ census_year,
    ncol = 4
  ) +
  labs(
    x = "津波被災農地割合",
    y = "20ha以上経営体割合"
  ) +
  theme_minimal()

ggsave(
  "tsunami_20ha.png",
  width = 18,
  height = 4,
  units = "cm",
  dpi = 300
)
```



```{r}
df2 <- df2 |>
  mutate(
    share_over_20ha = entities_over_20_0ha / entities_total
  )

ggplot(
  df2 ,
  aes(
    x = tsunami_farmland_share,
    y = share_over_20ha
  )
) +
  geom_point() +
  geom_smooth(
    method = "lm",
    se = FALSE
  ) +
  facet_wrap(~ census_year, ncol = 4) +
  labs(
    x = "津波被災農地割合",
    y = "20ha以上経営体割合"
  ) +
  theme_minimal()
```


```{r}
names(by_farm_size_2010)[
  sapply(
    df,
    function(x) any(as.character(x) == "FALSE", na.rm = TRUE)
  )
]
```

```{r}
df |> count(census_year)
```


```{r}
df2 |> filter(census_year=="2020") 

```


```{r}
df2 |> filter(area_name == "七ヶ浜町") |> 
  select(c(entities_over_30_0ha))
```


```{r}
machinery_change$individual_2015_2010_ratio
```


```{r}
machinery_change |>
  count(
    min_machine = case_when(
      individual_combine_owner_share_min_2010 <=
        individual_tractor_owner_share_min_2010 &
      individual_combine_owner_share_min_2010 <=
        individual_rice_transplanter_owner_share_min_2010 ~ "combine",

      individual_tractor_owner_share_min_2010 <=
        individual_rice_transplanter_owner_share_min_2010 ~ "tractor",

      TRUE ~ "rice_transplanter"
    )
  )
```



```{r}
m <- lm(
  individual_2015_2010_ratio ~
    individual_share_2010 +
    tsunami_farmland_share_2010 +
    c_one +
    c_four +
    production_support +
    individual_combine_owner_share_min_2010 +
    individual_tractor_owner_share_min_2010 +
    individual_rice_transplanter_owner_share_min_2010,
  data = machinery_change,
  weights = individual_entities_2010
)

m |> summary()
vif(m)
```



```{r}
df2 |> filter(census_year == "2010") |> 
  filter(area_name == "山下村")
```

```{r}
names(machinery_change)[
  grepl("individual_entities", names(machinery_change))
]
```



```{r}
machinery_change <- machinery_change |>
  mutate(
    tsunami_c =
      tsunami_farmland_share_2010 -
      mean(tsunami_farmland_share_2010, na.rm = TRUE),

    combine_owner_min_c =
      individual_combine_owner_share_min_2010 -
      mean(individual_combine_owner_share_min_2010, na.rm = TRUE)
  )

m_individual3 <- lm(
  individual_share_2015 ~
    individual_share_2010 +
    c_four * combine_owner_min_c,
  data = machinery_change
)

summary(m_individual3)

cor(
  machinery_change$individual_share_2010,
  machinery_change$individual_combine_owner_share_min_2010,
  use = "complete.obs"
)

car::vif(m_individual3)
```

```{r}
machinery_change <- machinery_change |>
  mutate(
    tsunami_c =
      tsunami_farmland_share_2015 -
      mean(tsunami_farmland_share_2015, na.rm = TRUE),

    combine_owner_min_c =
      individual_combine_owner_share_min_2015 -
      mean(individual_combine_owner_share_min_2015, na.rm = TRUE)
  )

m_individual4 <- lm(
  individual_share_2015 ~
    individual_share_2010 +
    c_four * combine_owner_min_c,
  data = machinery_change
)

summary(m_individual4)

cor(
  machinery_change$individual_share_2010,
  machinery_change$individual_combine_owner_share_min_2010,
  use = "complete.obs"
)

car::vif(m_individual4)
```

```{r}
m <- lm(
  change_share_over_10ha ~
    change_individual_share * c_one +
    tsunami_farmland_share +
    farmland_total_by_kcity,
  data = df_change2
)

summary(m)
```


```{r}
m <- lm(
  change_share_over_10ha ~
    change_individual_share * c_four +
    tsunami_farmland_share +
    farmland_total_by_kcity,
  data = df_change2
)

summary(m)
```


```{r}

df2 <- df2 |>
  mutate(
    share_over_20ha = entities_over_20_0ha / entities_total
  )

change_20ha <- df2 |>
  filter(census_year %in% c("2010", "2020")) |>
  select(
    area_code,
    census_year,
    share_over_20ha,
    tsunami_farmland_share,
    c_one,
    c_four,
    farmland_total_by_kcity
  ) |>
  tidyr::pivot_wider(
    id_cols = c(
      area_code,
      tsunami_farmland_share,
      c_one,
      c_four,
      farmland_total_by_kcity
    ),
    names_from = census_year,
    values_from = share_over_20ha,
    names_prefix = "share_"
  ) |>
  mutate(
    change_2010_2020 = share_2020 - share_2010
  )

m13 <- lm(
  change_2010_2020 ~
    tsunami_farmland_share +
    c_one +
    c_four +
    tsunami_farmland_share:c_one +
    tsunami_farmland_share:c_four,
  data = change_20ha
)

summary(m13)
vif(m13)
```



```{r}
change_20ha <- change_20ha |>
  mutate(
    tsunami_c = tsunami_farmland_share -
      mean(tsunami_farmland_share, na.rm = TRUE)
  )
  
m1 <- lm(
  change_2010_2020 ~
    tsunami_c * c_one +
    c_four,
  data = change_20ha
)

m1 |> summary()
vif(m1)
```



```{r}
change_20ha <- change_20ha |>
  mutate(
    tsunami_c = tsunami_farmland_share -
      mean(tsunami_farmland_share, na.rm = TRUE)
  )
  
m1 <- lm(
  change_2010_2020 ~
    tsunami_c +
    c_one*c_four,
  data = change_20ha
)

m1 |> summary()
vif(m1)
```


```{r}
df2 |>
  filter(
    census_year == "2020",
    !is.na(c_one),
    tsunami_farmland_share > 0
  ) |>
  mutate(
    share_over_10ha = entities_over_10_0ha / entities_total,
    c_one = factor(
      c_one,
      levels = c(1, 0),
      labels = c("C-1実施", "C-1非実施")
    )
  ) |>
  ggplot(
    aes(
      x = tsunami_farmland_share,
      y = share_over_10ha,
      shape = c_one,
      linetype = c_one
    )
  ) +
  geom_point(size = 3) +
  geom_smooth(
    method = "lm",
    se = FALSE
  ) +
  scale_shape_manual(
    values = c(
      "C-1実施" = 16,    # ○
      "C-1非実施" = 17   # △
    )
  ) +
  scale_linetype_manual(
    values = c(
      "C-1実施" = "solid",
      "C-1非実施" = "dashed"
    )
  ) +
  labs(
    x = "津波被災農地割合",
    y = "10ha以上経営体割合",
    shape = "C-1事業",
    linetype = "C-1事業"
  )
```

```{r}
df2 |>
  filter(
    census_year == "2020",
    !is.na(c_one),
    tsunami_farmland_share > 0
  ) |>
  group_by(c_one) |>
  summarise(
    n = n(),
    mean_damage = mean(tsunami_farmland_share, na.rm = TRUE),
    median_damage = median(tsunami_farmland_share, na.rm = TRUE),
    min_damage = min(tsunami_farmland_share, na.rm = TRUE),
    max_damage = max(tsunami_farmland_share, na.rm = TRUE)
  )
```


```{r}
df2 |>
  filter(
    census_year == "2020",
    !is.na(c_one),
    tsunami_farmland_share > 0
  ) |>
  ggplot(
    aes(
      x = factor(c_one),
      y = tsunami_farmland_share
    )
  ) +
  geom_boxplot() +
  geom_jitter(width = 0.1) +
  labs(
    x = "C-1事業",
    y = "津波被災農地割合"
  )
```

```{r}
c1_model <- df2 |>
  filter(
    census_year == "2010",
    !is.na(c_one),
    tsunami_farmland_share > 0
  ) |>
  glm(
    c_one ~ tsunami_farmland_share,
    family = binomial,
    data = _
  )

summary(c1_model)
```

```{r}
c1_model <- df2 |>
  filter(
    census_year == "2010",
    !is.na(c_one),
    tsunami_farmland_share > 0
  ) |>
  glm(
    c_one ~ tsunami_farmland_share +
          tunami_farmland_total_by_kcity,
    family = binomial,
    data = _
  )

summary(c1_model)
```


```{r}
large_farm_summary <- df2 |>
  group_by(census_year, area_code) |>
  summarise(
    entities_total = sum(entities_total, na.rm = TRUE),
    entities_over_10_0ha = sum(entities_over_10_0ha, na.rm = TRUE),
    share_over_10_0ha =
      round(entities_over_10_0ha / entities_total * 100,1),
    .groups = "drop"
  )
large_farm_summary
```


```{r}
df |> filter(area_name == "志津川町")
```


```{r}

# 旧市区町村コードが00で下位区分にも旧町村がある、という地域を取り除く
# たとえば気仙沼市（205-00）には下位区分の鹿折町（205-02）などがある。津波被災を表すGISデータでは、津波被災状況のデータが下位区分の町村の方には含まれるが、上位（たとえば気仙沼市（205-00））には含まれないので、そのままだと気仙沼市の津波被災農地面積がNAと表示されてしまう。
df <- df |>
  mutate(
    city_code = substr(area_code, 1, 3),
    kcity_code = substr(area_code, 5, 6)
  )

df <- df |>
  group_by(city_code) |>
  mutate(
    has_subarea = any(kcity_code != "00")
  ) |>
  ungroup()

df <- df |>
  filter(!(kcity_code == "00" & has_subarea))
```


```{r}
df |>
  filter(substr(area_code, 1, 3) == "205") |>
  select(area_name, area_code, farmland_total_by_kcity)

df |>
  filter(substr(area_code, 1, 3) == "202") |>
  filter(area_code != "205-00") |>
  distinct(area_code, farmland_total_by_kcity) |>
  summarise(
    farmland_total = sum(farmland_total_by_kcity, na.rm = TRUE)
  )
```


```{r}
df |> filter(census_year == "2010") |>
  arrange(desc(tsunami_farmland_share)) |>
  select(
    area_name, 
    area_code,
    farmland_total_by_kcity,
    tunami_farmland_total_by_kcity,
    tsunami_farmland_share
  )
```


```{r}
# 旧市区町村ごとの農地面積
farmland_total_by_kcity <- read_csv("02_processed_data/farmland_total_by_kcity.csv")

# 旧市区町村ごとの津波被災農地面積
tunami_farmland_total_by_kcity <- read_csv("02_processed_data/tsunami_farmland_total_by_kcity.csv")

# area_codeに重複がないことをチェック
farmland_total_by_kcity |> count(area_code) |> filter(n > 1)
tunami_farmland_total_by_kcity |> count(area_code) |> filter(n > 1)


# 両データフレームを結合し、津波被災農地割合を求める
tsunami_farmland_by_kcity <-
  farmland_total_by_kcity |>
  left_join(
    tunami_farmland_total_by_kcity,
    by = "area_code"
  ) |>
  mutate(
    tsunami_farmland_share =
      round(tunami_farmland_total_by_kcity / farmland_total_by_kcity, 2),
      round(farmland_total_by_kcity, 3), 
      round(tunami_farmland_total_by_kcity, 3)
  )

# 割合の値がおかしくなっていないことをチェック
tsunami_farmland_by_kcity |>
  summarise(
    min_share = min(tsunami_farmland_share, na.rm = TRUE),
    max_share = max(tsunami_farmland_share, na.rm = TRUE)
  )

# dfに結合
df <- df |>
  left_join(
    tsunami_farmland_by_kcity |>
      select(area_code, 
             farmland_total_by_kcity, 
             tunami_farmland_total_by_kcity,
             tsunami_farmland_share),
    by = "area_code"
  )

```


```{r}
df2 |> filter(area_name == "七ヶ浜町")
```


```{r}
df2 |> filter(census_year == "2010") |>
  select(
    census_year,
    area_code,
    area_name,
    entities_total,
    entities_over_5_0ha,
    share_over_5_0ha
  ) |>
  arrange( desc(share_over_5_0ha))
```

```{r}
area_classification <- df |>
  mutate(
    census_year = as.integer(census_year)
  ) |>
  group_by(area_code) |>
  slice_max(
    order_by = census_year,
    n = 1,
    with_ties = FALSE
  ) |>
  ungroup() |>
  select(area_code, area_name) |>
  arrange(area_code) |>
  mutate(
    coastal_area = NA_integer_,
    judgment = NA_character_,
    note = NA_character_
  )


area_classification |>
  count(area_code) |>
  filter(n > 1)

write_xlsx(
  area_classification,
  "area_classification.xlsx"
)
```


```{r}
large_farm_summary <- df2 |>
  group_by(census_year) |>
  summarise(
    entities_total = sum(entities_total, na.rm = TRUE),
    entities_over_5_0ha = sum(entities_over_5_0ha, na.rm = TRUE),
    share_over_5_0ha =
      entities_over_5_0ha / entities_total * 100,
    .groups = "drop"
  )
large_farm_summary
```



