---
title: "qca_largescale2"
output: html_document
date: "2026-09-02"
---

# ライブラリ

```{r}
library(tidyverse)
library(QCA)
```



# source

```{r}
df_qca <- read_csv("02_processed_data/shichigahama_qca_largescale2.csv")
df_qca
```

# 後継者欠損データを控除した分析

まず後継者欠損のデータ控除したデータフレームを作成。

```{r}
vars <- c("name", "indint", "largescale2", "mechcap", "agecap")

# 各変数の欠損数
colSums(is.na(df_qca[vars]))

# 分析に使用できるケース
df_qca_complete <- df_qca[complete.cases(df_qca[vars]), vars]

nrow(df_qca_complete)
df_qca_complete
```

## 肯定アウトカムの分析

### 真理値表を求める

```{r}
tt <- truthTable(
  df_qca_complete,
  outcome = "indint",
  conditions = c("largescale2", "mechcap", "agecap"),
  incl.cut = 0.80,
  n.cut = 1,
  show.cases = TRUE,
  complete = TRUE
)

tt
```
### 複雑解を求める

```{r}
sol_complex <- minimize(
  tt,
  details = TRUE,
  show.cases = TRUE
)

sol_complex
```

largescale2は消えて、やはり機械×年齢が残る

### 必要条件分析

```{r}
df_qca_nec <- as.data.frame(
  df_qca_complete[, c(
    "indint", "largescale2", "mechcap", "agecap"
  )]
)

nec <- pofind(
  data = df_qca_nec,
  outcome = "indint",
  conditions = c("largescale2", "mechcap", "agecap"),
  relation = "necessity"
)

nec
```

ただ、largescale2は単独では必要条件として重要。

